// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/frontend.proto

package frontend

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Frontend service

func NewFrontendEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Frontend service

type FrontendService interface {
}

type frontendService struct {
	c    client.Client
	name string
}

func NewFrontendService(name string, c client.Client) FrontendService {
	return &frontendService{
		c:    c,
		name: name,
	}
}

// Server API for Frontend service

type FrontendHandler interface {
}

func RegisterFrontendHandler(s server.Server, hdlr FrontendHandler, opts ...server.HandlerOption) error {
	type frontend interface {
	}
	type Frontend struct {
		frontend
	}
	h := &frontendHandler{hdlr}
	return s.Handle(s.NewHandler(&Frontend{h}, opts...))
}

type frontendHandler struct {
	FrontendHandler
}
