version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./backend/.env

  frontend_proxy:
    build:
      context: backend
      dockerfile: services/frontend/Dockerfile
    container_name: kioku-frontend_proxy
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  user_service:
    build:
      context: backend
      dockerfile: services/user/Dockerfile
    container_name: kioku-user_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
  
  carddeck_service:
    build:
      context: backend
      dockerfile: services/carddeck/Dockerfile
    container_name: kioku-carddeck_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  collaboration_service:
    build:
      context: backend
      dockerfile: services/collaboration/Dockerfile
    container_name: kioku-collaboration_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  srs_service:
    build:
      context: backend
      dockerfile: services/srs/Dockerfile
    container_name: kioku-srs_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  notifications_service:
    build:
      context: backend
      dockerfile: services/notifications/Dockerfile
    container_name: kioku-notifications_service
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: frontend
    container_name: kioku-frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - frontend_proxy
      - user_service
      - carddeck_service
      - collaboration_service
  
  go-micro-dashboard:
    image: xpunch/go-micro-dashboard:latest
    container_name: kioku-micro-dashboard
    ports:
      - "127.0.0.1:3001:8082"
    env_file:
      - ./backend/.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: kioku-pgadmin
    restart: always
    ports:
      - "127.0.0.1:3002:80"
    env_file:
      - ./backend/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
