FROM golang:1.19.3-bullseye

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod graph | awk '{if ($1 !~ "@") print $2}' | xargs go get

COPY . .

RUN go build -o /kioku_server /app/cmd/server/main.go

ENTRYPOINT [ "/kioku_server" ]