// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: services/user/proto/user.proto

package user

import (
	fmt "fmt"
	proto1 "github.com/kioku-project/kioku/pkg/proto"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	Register(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error)
	DeleteUser(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error)
	Login(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.User, error)
	GetUserIDFromEmail(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.User, error)
	GetUserInformation(ctx context.Context, in *proto1.Users, opts ...client.CallOption) (*proto1.Users, error)
	GetUserProfileInformation(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.User, error)
	ModifyUserProfileInformation(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error)
	VerifyUserExists(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "User.Register", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUser(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "User.DeleteUser", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.User, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(proto1.User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserIDFromEmail(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.User, error) {
	req := c.c.NewRequest(c.name, "User.GetUserIDFromEmail", in)
	out := new(proto1.User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInformation(ctx context.Context, in *proto1.Users, opts ...client.CallOption) (*proto1.Users, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInformation", in)
	out := new(proto1.Users)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserProfileInformation(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.User, error) {
	req := c.c.NewRequest(c.name, "User.GetUserProfileInformation", in)
	out := new(proto1.User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ModifyUserProfileInformation(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "User.ModifyUserProfileInformation", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) VerifyUserExists(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "User.VerifyUserExists", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Register(context.Context, *proto1.User, *proto1.Success) error
	DeleteUser(context.Context, *proto1.User, *proto1.Success) error
	Login(context.Context, *proto1.User, *proto1.User) error
	GetUserIDFromEmail(context.Context, *proto1.User, *proto1.User) error
	GetUserInformation(context.Context, *proto1.Users, *proto1.Users) error
	GetUserProfileInformation(context.Context, *proto1.User, *proto1.User) error
	ModifyUserProfileInformation(context.Context, *proto1.User, *proto1.Success) error
	VerifyUserExists(context.Context, *proto1.User, *proto1.Success) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Register(ctx context.Context, in *proto1.User, out *proto1.Success) error
		DeleteUser(ctx context.Context, in *proto1.User, out *proto1.Success) error
		Login(ctx context.Context, in *proto1.User, out *proto1.User) error
		GetUserIDFromEmail(ctx context.Context, in *proto1.User, out *proto1.User) error
		GetUserInformation(ctx context.Context, in *proto1.Users, out *proto1.Users) error
		GetUserProfileInformation(ctx context.Context, in *proto1.User, out *proto1.User) error
		ModifyUserProfileInformation(ctx context.Context, in *proto1.User, out *proto1.Success) error
		VerifyUserExists(ctx context.Context, in *proto1.User, out *proto1.Success) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Register(ctx context.Context, in *proto1.User, out *proto1.Success) error {
	return h.UserHandler.Register(ctx, in, out)
}

func (h *userHandler) DeleteUser(ctx context.Context, in *proto1.User, out *proto1.Success) error {
	return h.UserHandler.DeleteUser(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *proto1.User, out *proto1.User) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *userHandler) GetUserIDFromEmail(ctx context.Context, in *proto1.User, out *proto1.User) error {
	return h.UserHandler.GetUserIDFromEmail(ctx, in, out)
}

func (h *userHandler) GetUserInformation(ctx context.Context, in *proto1.Users, out *proto1.Users) error {
	return h.UserHandler.GetUserInformation(ctx, in, out)
}

func (h *userHandler) GetUserProfileInformation(ctx context.Context, in *proto1.User, out *proto1.User) error {
	return h.UserHandler.GetUserProfileInformation(ctx, in, out)
}

func (h *userHandler) ModifyUserProfileInformation(ctx context.Context, in *proto1.User, out *proto1.Success) error {
	return h.UserHandler.ModifyUserProfileInformation(ctx, in, out)
}

func (h *userHandler) VerifyUserExists(ctx context.Context, in *proto1.User, out *proto1.Success) error {
	return h.UserHandler.VerifyUserExists(ctx, in, out)
}
