mode: production

database:
  name: kioku-database
  containerName: postgres

  image: postgres
  tag: latest

  replicaCount: 1

  port: 5432

  size: 10Gi
  mountPath: /mnt/data

  secret:
    name: kioku-database-secret

frontend:
  name: kioku-frontend
  image: ghcr.io/kioku-project/kioku_frontend
  tag: prod
  port: 80
  containerPort: 3000

  httpPath: /

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

frontend_proxy:
  name: kioku-frontend-proxy
  image: ghcr.io/kioku-project/kioku_frontend_proxy
  tag: feature-tracing
  httpPath: /api

  keySecret: frontend-proxy-key-secret

  port: 80
  containerPort: 80

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50


carddeck:
  name: kioku-carddeck
  image: ghcr.io/kioku-project/kioku_carddeck
  tag: feature-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

user:
  name: kioku-user
  image: ghcr.io/kioku-project/kioku_user
  tag: feature-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

collaboration:
  name: kioku-collaboration
  image: ghcr.io/kioku-project/kioku_collaboration
  tag: feature-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50
