mode: production

cassandra:
  username: cassandra
  password: cassandra

database:
  name: kioku-database

  databaseName: kioku
  userName: kioku

  instances: 1

  size: 10Gi
  mountPath: /mnt/data

  secret:
    name: kioku-database-secret

frontend:
  name: kioku-frontend
  image: ghcr.io/kioku-project/kioku_frontend
  tag: prod
  port: 80
  containerPort: 3000

  httpPath: /

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 200

frontend_proxy:
  name: kioku-frontend-proxy
  image: ghcr.io/kioku-project/kioku_frontend_proxy
  tag: feat-db-tracing
  httpPath: /api

  keySecret: frontend-proxy-key-secret

  port: 80
  containerPort: 80

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 200


carddeck:
  name: kioku-carddeck
  image: ghcr.io/kioku-project/kioku_carddeck
  tag: feat-db-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 200

srs:
  name: kioku-srs
  image: ghcr.io/kioku-project/kioku_srs
  tag: feat-db-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 200

user:
  name: kioku-user
  image: ghcr.io/kioku-project/kioku_user
  tag: feat-db-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 200

collaboration:
  name: kioku-collaboration
  image: ghcr.io/kioku-project/kioku_collaboration
  tag: feat-db-tracing

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 200
