mode: latestuction

vapidSecret: vapid-secret

cassandra:
  username: cassandra
  password: cassandra

database:
  name: kioku-database

  databaseName: kioku
  userName: kioku

  instances: 2

  size: 10Gi
  mountPath: /mnt/data

  secret:
    name: kioku-database-secret

frontend:
  name: kioku-frontend
  image: kioku-frontend
  tag: latest
  port: 80
  containerPort: 3000

  httpPath: /

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

frontend_proxy:
  name: kioku-frontend-proxy
  image: kioku-frontend_proxy
  tag: latest
  httpPath: /api

  keySecret: frontend-proxy-key-secret

  port: 80
  containerPort: 8090

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

carddeck:
  name: kioku-carddeck
  image: kioku-carddeck_service
  tag: latest

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

srs:
  name: kioku-srs
  image: kioku-srs_service
  tag: latest

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

notification:
  name: kioku-notification
  image: kioku-notification_service
  tag: latest

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

user:
  name: kioku-user
  image: kioku-user_service
  tag: latest

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50

collaboration:
  name: kioku-collaboration
  image: kioku-collaboration_service
  tag: latest

  autoscaler:
    min: 1
    max: 10
    targetCPUUtilizationPercentage: 50
