// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: proto/srs.proto

package srs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeckPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeckID string `protobuf:"bytes,2,opt,name=deckID,proto3" json:"deckID,omitempty"`
}

func (x *DeckPullRequest) Reset() {
	*x = DeckPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckPullRequest) ProtoMessage() {}

func (x *DeckPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckPullRequest.ProtoReflect.Descriptor instead.
func (*DeckPullRequest) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{0}
}

func (x *DeckPullRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeckPullRequest) GetDeckID() string {
	if x != nil {
		return x.DeckID
	}
	return ""
}

type SrsPullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *SrsPullResponse) Reset() {
	*x = SrsPullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrsPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrsPullResponse) ProtoMessage() {}

func (x *SrsPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrsPullResponse.ProtoReflect.Descriptor instead.
func (*SrsPullResponse) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{1}
}

func (x *SrsPullResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type DueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Due int64 `protobuf:"varint,1,opt,name=due,proto3" json:"due,omitempty"`
}

func (x *DueResponse) Reset() {
	*x = DueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DueResponse) ProtoMessage() {}

func (x *DueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DueResponse.ProtoReflect.Descriptor instead.
func (*DueResponse) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{2}
}

func (x *DueResponse) GetDue() int64 {
	if x != nil {
		return x.Due
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardID string  `protobuf:"bytes,1,opt,name=cardID,proto3" json:"cardID,omitempty"`
	Sides  []*Side `protobuf:"bytes,2,rep,name=sides,proto3" json:"sides,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetCardID() string {
	if x != nil {
		return x.CardID
	}
	return ""
}

func (x *Card) GetSides() []*Side {
	if x != nil {
		return x.Sides
	}
	return nil
}

type Side struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Side) Reset() {
	*x = Side{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Side) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Side) ProtoMessage() {}

func (x *Side) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Side.ProtoReflect.Descriptor instead.
func (*Side) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{4}
}

func (x *Side) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Side) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SrsPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CardID string `protobuf:"bytes,2,opt,name=cardID,proto3" json:"cardID,omitempty"`
	DeckID string `protobuf:"bytes,3,opt,name=deckID,proto3" json:"deckID,omitempty"`
	Rating int64  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *SrsPushRequest) Reset() {
	*x = SrsPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SrsPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrsPushRequest) ProtoMessage() {}

func (x *SrsPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrsPushRequest.ProtoReflect.Descriptor instead.
func (*SrsPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{5}
}

func (x *SrsPushRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SrsPushRequest) GetCardID() string {
	if x != nil {
		return x.CardID
	}
	return ""
}

func (x *SrsPushRequest) GetDeckID() string {
	if x != nil {
		return x.DeckID
	}
	return ""
}

func (x *SrsPushRequest) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type SuccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{6}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BindingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CardID string `protobuf:"bytes,2,opt,name=cardID,proto3" json:"cardID,omitempty"`
	DeckID string `protobuf:"bytes,3,opt,name=deckID,proto3" json:"deckID,omitempty"`
}

func (x *BindingRequest) Reset() {
	*x = BindingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_srs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingRequest) ProtoMessage() {}

func (x *BindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_srs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingRequest.ProtoReflect.Descriptor instead.
func (*BindingRequest) Descriptor() ([]byte, []int) {
	return file_proto_srs_proto_rawDescGZIP(), []int{7}
}

func (x *BindingRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BindingRequest) GetCardID() string {
	if x != nil {
		return x.CardID
	}
	return ""
}

func (x *BindingRequest) GetDeckID() string {
	if x != nil {
		return x.DeckID
	}
	return ""
}

var File_proto_srs_proto protoreflect.FileDescriptor

var file_proto_srs_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x73, 0x72, 0x73, 0x22, 0x41, 0x0a, 0x0f, 0x44, 0x65, 0x63, 0x6b, 0x50, 0x75,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x0f, 0x53, 0x72, 0x73,
	0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x72, 0x73,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x1f, 0x0a, 0x0b, 0x44,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x64, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x04,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44, 0x12, 0x1f, 0x0a, 0x05,
	0x73, 0x69, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x72,
	0x73, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x05, 0x73, 0x69, 0x64, 0x65, 0x73, 0x22, 0x40, 0x0a,
	0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x70, 0x0a, 0x0e, 0x53, 0x72, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x58,
	0x0a, 0x0e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x44, 0x32, 0xf0, 0x01, 0x0a, 0x03, 0x53, 0x72, 0x73,
	0x12, 0x33, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x13, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x53,
	0x72, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x73, 0x72, 0x73, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x14, 0x2e,
	0x73, 0x72, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x53, 0x72, 0x73, 0x50, 0x75, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x13, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x63, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x73, 0x44, 0x75,
	0x65, 0x12, 0x14, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x6b, 0x50, 0x75, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x73, 0x72, 0x73, 0x2e, 0x44, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x73, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_srs_proto_rawDescOnce sync.Once
	file_proto_srs_proto_rawDescData = file_proto_srs_proto_rawDesc
)

func file_proto_srs_proto_rawDescGZIP() []byte {
	file_proto_srs_proto_rawDescOnce.Do(func() {
		file_proto_srs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_srs_proto_rawDescData)
	})
	return file_proto_srs_proto_rawDescData
}

var file_proto_srs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_srs_proto_goTypes = []interface{}{
	(*DeckPullRequest)(nil), // 0: srs.DeckPullRequest
	(*SrsPullResponse)(nil), // 1: srs.SrsPullResponse
	(*DueResponse)(nil),     // 2: srs.DueResponse
	(*Card)(nil),            // 3: srs.Card
	(*Side)(nil),            // 4: srs.Side
	(*SrsPushRequest)(nil),  // 5: srs.SrsPushRequest
	(*SuccessResponse)(nil), // 6: srs.SuccessResponse
	(*BindingRequest)(nil),  // 7: srs.BindingRequest
}
var file_proto_srs_proto_depIdxs = []int32{
	3, // 0: srs.SrsPullResponse.card:type_name -> srs.Card
	4, // 1: srs.Card.sides:type_name -> srs.Side
	5, // 2: srs.Srs.Push:input_type -> srs.SrsPushRequest
	0, // 3: srs.Srs.Pull:input_type -> srs.DeckPullRequest
	7, // 4: srs.Srs.AddUserCardBinding:input_type -> srs.BindingRequest
	0, // 5: srs.Srs.GetDeckCardsDue:input_type -> srs.DeckPullRequest
	6, // 6: srs.Srs.Push:output_type -> srs.SuccessResponse
	1, // 7: srs.Srs.Pull:output_type -> srs.SrsPullResponse
	6, // 8: srs.Srs.AddUserCardBinding:output_type -> srs.SuccessResponse
	2, // 9: srs.Srs.GetDeckCardsDue:output_type -> srs.DueResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_srs_proto_init() }
func file_proto_srs_proto_init() {
	if File_proto_srs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_srs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrsPullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Side); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SrsPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_srs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_srs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_srs_proto_goTypes,
		DependencyIndexes: file_proto_srs_proto_depIdxs,
		MessageInfos:      file_proto_srs_proto_msgTypes,
	}.Build()
	File_proto_srs_proto = out.File
	file_proto_srs_proto_rawDesc = nil
	file_proto_srs_proto_goTypes = nil
	file_proto_srs_proto_depIdxs = nil
}
