export default function Cards() {
	return (
		<svg
			width="40vw"
			height="h-full"
			viewBox="0 0 514 680"
			fill="none"
			xmlns="http://www.w3.org/2000/svg"
		>
			<rect
				x="4"
				y="276"
				width="300"
				height="400"
				rx="7"
				fill="#FFFFF3"
				stroke="#9EADC8"
				stroke-width="8"
				className="drop-shadow-2xl"
			/>
			<rect
				x="210"
				y="147"
				width="300"
				height="400"
				rx="7"
				fill="#FFFFF3"
				stroke="#F3A712"
				stroke-width="8"
				className="drop-shadow-2xl"
			/>
			<rect
				x="82"
				y="4"
				width="300"
				height="400"
				rx="13"
				fill="#FFFFF3"
				stroke="#29335C"
				stroke-width="8"
				className="drop-shadow-2xl"
			/>
		</svg>
	);
}
