// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: services/staticSrs/proto/static-srs.proto

package staticSrs

import (
	fmt "fmt"
	proto1 "github.com/kioku-project/kioku/pkg/proto"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StaticSrs service

func NewStaticSrsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StaticSrs service

type StaticSrsService interface {
	Push(ctx context.Context, in *proto1.SrsPushRequest, opts ...client.CallOption) (*proto1.Success, error)
	Pull(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.Card, error)
	AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, opts ...client.CallOption) (*proto1.Success, error)
	GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.UserDueResponse, error)
	GetUserCardsDue(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.UserDueResponse, error)
}

type staticSrsService struct {
	c    client.Client
	name string
}

func NewStaticSrsService(name string, c client.Client) StaticSrsService {
	return &staticSrsService{
		c:    c,
		name: name,
	}
}

func (c *staticSrsService) Push(ctx context.Context, in *proto1.SrsPushRequest, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "StaticSrs.Push", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticSrsService) Pull(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.Card, error) {
	req := c.c.NewRequest(c.name, "StaticSrs.Pull", in)
	out := new(proto1.Card)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticSrsService) AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "StaticSrs.AddUserCardBinding", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticSrsService) GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.UserDueResponse, error) {
	req := c.c.NewRequest(c.name, "StaticSrs.GetDeckCardsDue", in)
	out := new(proto1.UserDueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticSrsService) GetUserCardsDue(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.UserDueResponse, error) {
	req := c.c.NewRequest(c.name, "StaticSrs.GetUserCardsDue", in)
	out := new(proto1.UserDueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StaticSrs service

type StaticSrsHandler interface {
	Push(context.Context, *proto1.SrsPushRequest, *proto1.Success) error
	Pull(context.Context, *proto1.DeckRequest, *proto1.Card) error
	AddUserCardBinding(context.Context, *proto1.BindingRequest, *proto1.Success) error
	GetDeckCardsDue(context.Context, *proto1.DeckRequest, *proto1.UserDueResponse) error
	GetUserCardsDue(context.Context, *proto1.User, *proto1.UserDueResponse) error
}

func RegisterStaticSrsHandler(s server.Server, hdlr StaticSrsHandler, opts ...server.HandlerOption) error {
	type staticSrs interface {
		Push(ctx context.Context, in *proto1.SrsPushRequest, out *proto1.Success) error
		Pull(ctx context.Context, in *proto1.DeckRequest, out *proto1.Card) error
		AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, out *proto1.Success) error
		GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, out *proto1.UserDueResponse) error
		GetUserCardsDue(ctx context.Context, in *proto1.User, out *proto1.UserDueResponse) error
	}
	type StaticSrs struct {
		staticSrs
	}
	h := &staticSrsHandler{hdlr}
	return s.Handle(s.NewHandler(&StaticSrs{h}, opts...))
}

type staticSrsHandler struct {
	StaticSrsHandler
}

func (h *staticSrsHandler) Push(ctx context.Context, in *proto1.SrsPushRequest, out *proto1.Success) error {
	return h.StaticSrsHandler.Push(ctx, in, out)
}

func (h *staticSrsHandler) Pull(ctx context.Context, in *proto1.DeckRequest, out *proto1.Card) error {
	return h.StaticSrsHandler.Pull(ctx, in, out)
}

func (h *staticSrsHandler) AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, out *proto1.Success) error {
	return h.StaticSrsHandler.AddUserCardBinding(ctx, in, out)
}

func (h *staticSrsHandler) GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, out *proto1.UserDueResponse) error {
	return h.StaticSrsHandler.GetDeckCardsDue(ctx, in, out)
}

func (h *staticSrsHandler) GetUserCardsDue(ctx context.Context, in *proto1.User, out *proto1.UserDueResponse) error {
	return h.StaticSrsHandler.GetUserCardsDue(ctx, in, out)
}
