// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/carddeck.proto

package carddeck

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Carddeck service

func NewCarddeckEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Carddeck service

type CarddeckService interface {
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...client.CallOption) (*IDResponse, error)
	ModifyCard(ctx context.Context, in *ModifyCardRequest, opts ...client.CallOption) (*SuccessResponse, error)
	DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...client.CallOption) (*SuccessResponse, error)
	CreateDeck(ctx context.Context, in *CreateDeckRequest, opts ...client.CallOption) (*IDResponse, error)
	ModifyDeck(ctx context.Context, in *ModifyDeckRequest, opts ...client.CallOption) (*SuccessResponse, error)
	DeleteDeck(ctx context.Context, in *DeckRequest, opts ...client.CallOption) (*SuccessResponse, error)
	GetDeckCards(ctx context.Context, in *DeckRequest, opts ...client.CallOption) (*DeckCardsResponse, error)
	GetGroupDecks(ctx context.Context, in *GroupDecksRequest, opts ...client.CallOption) (*GroupDecksResponse, error)
}

type carddeckService struct {
	c    client.Client
	name string
}

func NewCarddeckService(name string, c client.Client) CarddeckService {
	return &carddeckService{
		c:    c,
		name: name,
	}
}

func (c *carddeckService) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...client.CallOption) (*IDResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.CreateCard", in)
	out := new(IDResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) ModifyCard(ctx context.Context, in *ModifyCardRequest, opts ...client.CallOption) (*SuccessResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.ModifyCard", in)
	out := new(SuccessResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...client.CallOption) (*SuccessResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.DeleteCard", in)
	out := new(SuccessResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) CreateDeck(ctx context.Context, in *CreateDeckRequest, opts ...client.CallOption) (*IDResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.CreateDeck", in)
	out := new(IDResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) ModifyDeck(ctx context.Context, in *ModifyDeckRequest, opts ...client.CallOption) (*SuccessResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.ModifyDeck", in)
	out := new(SuccessResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) DeleteDeck(ctx context.Context, in *DeckRequest, opts ...client.CallOption) (*SuccessResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.DeleteDeck", in)
	out := new(SuccessResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) GetDeckCards(ctx context.Context, in *DeckRequest, opts ...client.CallOption) (*DeckCardsResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.GetDeckCards", in)
	out := new(DeckCardsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carddeckService) GetGroupDecks(ctx context.Context, in *GroupDecksRequest, opts ...client.CallOption) (*GroupDecksResponse, error) {
	req := c.c.NewRequest(c.name, "Carddeck.GetGroupDecks", in)
	out := new(GroupDecksResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Carddeck service

type CarddeckHandler interface {
	CreateCard(context.Context, *CreateCardRequest, *IDResponse) error
	ModifyCard(context.Context, *ModifyCardRequest, *SuccessResponse) error
	DeleteCard(context.Context, *DeleteCardRequest, *SuccessResponse) error
	CreateDeck(context.Context, *CreateDeckRequest, *IDResponse) error
	ModifyDeck(context.Context, *ModifyDeckRequest, *SuccessResponse) error
	DeleteDeck(context.Context, *DeckRequest, *SuccessResponse) error
	GetDeckCards(context.Context, *DeckRequest, *DeckCardsResponse) error
	GetGroupDecks(context.Context, *GroupDecksRequest, *GroupDecksResponse) error
}

func RegisterCarddeckHandler(s server.Server, hdlr CarddeckHandler, opts ...server.HandlerOption) error {
	type carddeck interface {
		CreateCard(ctx context.Context, in *CreateCardRequest, out *IDResponse) error
		ModifyCard(ctx context.Context, in *ModifyCardRequest, out *SuccessResponse) error
		DeleteCard(ctx context.Context, in *DeleteCardRequest, out *SuccessResponse) error
		CreateDeck(ctx context.Context, in *CreateDeckRequest, out *IDResponse) error
		ModifyDeck(ctx context.Context, in *ModifyDeckRequest, out *SuccessResponse) error
		DeleteDeck(ctx context.Context, in *DeckRequest, out *SuccessResponse) error
		GetDeckCards(ctx context.Context, in *DeckRequest, out *DeckCardsResponse) error
		GetGroupDecks(ctx context.Context, in *GroupDecksRequest, out *GroupDecksResponse) error
	}
	type Carddeck struct {
		carddeck
	}
	h := &carddeckHandler{hdlr}
	return s.Handle(s.NewHandler(&Carddeck{h}, opts...))
}

type carddeckHandler struct {
	CarddeckHandler
}

func (h *carddeckHandler) CreateCard(ctx context.Context, in *CreateCardRequest, out *IDResponse) error {
	return h.CarddeckHandler.CreateCard(ctx, in, out)
}

func (h *carddeckHandler) ModifyCard(ctx context.Context, in *ModifyCardRequest, out *SuccessResponse) error {
	return h.CarddeckHandler.ModifyCard(ctx, in, out)
}

func (h *carddeckHandler) DeleteCard(ctx context.Context, in *DeleteCardRequest, out *SuccessResponse) error {
	return h.CarddeckHandler.DeleteCard(ctx, in, out)
}

func (h *carddeckHandler) CreateDeck(ctx context.Context, in *CreateDeckRequest, out *IDResponse) error {
	return h.CarddeckHandler.CreateDeck(ctx, in, out)
}

func (h *carddeckHandler) ModifyDeck(ctx context.Context, in *ModifyDeckRequest, out *SuccessResponse) error {
	return h.CarddeckHandler.ModifyDeck(ctx, in, out)
}

func (h *carddeckHandler) DeleteDeck(ctx context.Context, in *DeckRequest, out *SuccessResponse) error {
	return h.CarddeckHandler.DeleteDeck(ctx, in, out)
}

func (h *carddeckHandler) GetDeckCards(ctx context.Context, in *DeckRequest, out *DeckCardsResponse) error {
	return h.CarddeckHandler.GetDeckCards(ctx, in, out)
}

func (h *carddeckHandler) GetGroupDecks(ctx context.Context, in *GroupDecksRequest, out *GroupDecksResponse) error {
	return h.CarddeckHandler.GetGroupDecks(ctx, in, out)
}
