// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: services/linearSrs/proto/linear-srs.proto

package linearSrs

import (
	fmt "fmt"
	proto1 "github.com/kioku-project/kioku/pkg/proto"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LinearSrs service

func NewLinearSrsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LinearSrs service

type LinearSrsService interface {
	Push(ctx context.Context, in *proto1.SrsPushRequest, opts ...client.CallOption) (*proto1.Success, error)
	Pull(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.Card, error)
	AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, opts ...client.CallOption) (*proto1.Success, error)
	GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.UserDueResponse, error)
	GetUserCardsDue(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.UserDueResponse, error)
}

type linearSrsService struct {
	c    client.Client
	name string
}

func NewLinearSrsService(name string, c client.Client) LinearSrsService {
	return &linearSrsService{
		c:    c,
		name: name,
	}
}

func (c *linearSrsService) Push(ctx context.Context, in *proto1.SrsPushRequest, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "LinearSrs.Push", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearSrsService) Pull(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.Card, error) {
	req := c.c.NewRequest(c.name, "LinearSrs.Pull", in)
	out := new(proto1.Card)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearSrsService) AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, opts ...client.CallOption) (*proto1.Success, error) {
	req := c.c.NewRequest(c.name, "LinearSrs.AddUserCardBinding", in)
	out := new(proto1.Success)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearSrsService) GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, opts ...client.CallOption) (*proto1.UserDueResponse, error) {
	req := c.c.NewRequest(c.name, "LinearSrs.GetDeckCardsDue", in)
	out := new(proto1.UserDueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearSrsService) GetUserCardsDue(ctx context.Context, in *proto1.User, opts ...client.CallOption) (*proto1.UserDueResponse, error) {
	req := c.c.NewRequest(c.name, "LinearSrs.GetUserCardsDue", in)
	out := new(proto1.UserDueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LinearSrs service

type LinearSrsHandler interface {
	Push(context.Context, *proto1.SrsPushRequest, *proto1.Success) error
	Pull(context.Context, *proto1.DeckRequest, *proto1.Card) error
	AddUserCardBinding(context.Context, *proto1.BindingRequest, *proto1.Success) error
	GetDeckCardsDue(context.Context, *proto1.DeckRequest, *proto1.UserDueResponse) error
	GetUserCardsDue(context.Context, *proto1.User, *proto1.UserDueResponse) error
}

func RegisterLinearSrsHandler(s server.Server, hdlr LinearSrsHandler, opts ...server.HandlerOption) error {
	type linearSrs interface {
		Push(ctx context.Context, in *proto1.SrsPushRequest, out *proto1.Success) error
		Pull(ctx context.Context, in *proto1.DeckRequest, out *proto1.Card) error
		AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, out *proto1.Success) error
		GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, out *proto1.UserDueResponse) error
		GetUserCardsDue(ctx context.Context, in *proto1.User, out *proto1.UserDueResponse) error
	}
	type LinearSrs struct {
		linearSrs
	}
	h := &linearSrsHandler{hdlr}
	return s.Handle(s.NewHandler(&LinearSrs{h}, opts...))
}

type linearSrsHandler struct {
	LinearSrsHandler
}

func (h *linearSrsHandler) Push(ctx context.Context, in *proto1.SrsPushRequest, out *proto1.Success) error {
	return h.LinearSrsHandler.Push(ctx, in, out)
}

func (h *linearSrsHandler) Pull(ctx context.Context, in *proto1.DeckRequest, out *proto1.Card) error {
	return h.LinearSrsHandler.Pull(ctx, in, out)
}

func (h *linearSrsHandler) AddUserCardBinding(ctx context.Context, in *proto1.BindingRequest, out *proto1.Success) error {
	return h.LinearSrsHandler.AddUserCardBinding(ctx, in, out)
}

func (h *linearSrsHandler) GetDeckCardsDue(ctx context.Context, in *proto1.DeckRequest, out *proto1.UserDueResponse) error {
	return h.LinearSrsHandler.GetDeckCardsDue(ctx, in, out)
}

func (h *linearSrsHandler) GetUserCardsDue(ctx context.Context, in *proto1.User, out *proto1.UserDueResponse) error {
	return h.LinearSrsHandler.GetUserCardsDue(ctx, in, out)
}
