apiVersion: v1
kind: Secret
metadata:
  name: cassandra-secret
  labels:
    {{- include "kioku.labels" . | nindent 4 }}
type: Opaque
data:
  cassandra-user: {{ .Values.cassandra.username | b64enc }}
  cassandra-password: {{ .Values.cassandra.password | b64enc }}