---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: observability
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  ingress:
    enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-config
  namespace: observability
data:
  TRACING_COLLECTOR: "simple-prod-collector.observability.svc.cluster.local:4318"