---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.notifications.name }}-deployment"
  labels:
    {{- include "kioku.notifications.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kioku.notifications.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kioku.notifications.labels" . | nindent 8 }}
    spec:
      serviceAccountName: go-micro
      containers:
      - name: {{ .Values.notifications.name }}
        image: "{{ .Values.notifications.image }}:{{ .Values.notifications.tag }}"
      {{ if eq .Values.mode "production" }}
        imagePullPolicy: Always
      {{ else }}
        imagePullPolicy: Never
      {{ end }}
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 50m
            memory: 50M
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PORT
            value: "8080"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ print "postgres." .Values.database.databaseName ".credentials.postgresql.acid.zalan.do" }}
                key: password

        envFrom:
          - secretRef:
              name: {{ .Values.database.secret.name }}
          - configMapRef:
              name: service-env
          - configMapRef:
              name: tracing-config
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.notifications.name }}-service"
spec:
  selector:
    {{- include "kioku.notifications.labels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: "hpa-{{ .Values.notifications.name }}-deployment"
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: "{{ .Values.notifications.name }}-deployment"
 minReplicas: {{ .Values.notifications.autoscaler.min }}
 maxReplicas: {{ .Values.notifications.autoscaler.max }}
 targetCPUUtilizationPercentage: {{ .Values.notifications.autoscaler.targetCPUUtilizationPercentage }}
