apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vapidSecret }}
  labels:
    {{- include "kioku.labels" . | nindent 4 }}
type: Opaque
data:
  VAPID_PUBLIC_KEY: "Base64 encoded public vapid key"
  VAPID_PRIVATE_KEY: "Base64 encoded private vapid key"
