name: Web-UI Service

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'frontend/**'


env:
  NEXT_PUBLIC_ENVIRONMENT: "production"

jobs:
  build-frontend:
    uses: ./.github/workflows/build_service.yml
    with:
      image-name: kioku_frontend
      image-tag: ${GITHUB_REF##*/}
      path: ./frontend